apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- files:
  - config.yaml
  name: configmap
  behavior: merge

images:
- name: main
  newName: todo